[package]
name = "light_switch"
version = "0.1.0"
authors = ["WorldSEnder <WorldSEnder@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
